name: audio_app_test
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.2.6"
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter

  mrumru:
    git:
      url: https://github.com/snggle/mrumru.git
      ref: dev

  # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: 8.1.6
  bloc_test: 9.1.7

  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  # https://pub.dev/packages/equatable
  equatable: 2.0.5

  # Small, easy to use and extensible logger which prints beautiful logs.
  # https://pub.dev/packages/logger
  logger: 2.4.0

  # A Flutter plugin for finding commonly used locations on the filesystem.
  # https://pub.dev/packages/path_provider
  path_provider: 2.1.4

  # Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
  # https://pub.dev/packages/permission_handler
  permission_handler: 11.0.1
  permission_handler_web: 0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # A build system for Dart code generation and modular compilation.
  # https://pub.dev/packages/build_runner
  build_runner: 2.4.6

flutter:
  uses-material-design: true